apiVersion: v1
kind: Pod
metadata:
  name: xaimachinetest
spec:
  containers:
  - name: demo
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:latest
    command: ["sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 16Gi
        cpu: "4"
        nvidia.com/gpu: "1"
      requests:
        memory: 16Gi
        cpu: "2"
        nvidia.com/gpu: "1"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8s-gpu-5.ucsc.edu
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-RTX-A6000
  tolerations:
  - effect: NoSchedule
    key: nautilus.io/gilpin-lab
    operator: Exists
