apiVersion: v1
kind: Pod
metadata:
  name: jonathan-carla-pod
spec:
  containers:
  - name: gpu-container
    image: carlasim/carla:latest
    command: ["sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 20Gi
        cpu: "16"
        nvidia.com/gpu: 1
      requests:
        memory: 20Gi
        cpu: "2"
        nvidia.com/gpu: 1
  restartPolicy: Never
